### ISSUE TITLE
[Suggestion] add a command line help, and switch to another printer

### ISSUE THREAD

**Issue by Wikinaut** [makevoid/paperbank#1]
[Suggestion] add a command line help, and switch to another printer.

**Comment by makevoid** [comment]
thanks for the suggestion

**Comment by Wikinaut** [comment]
I mean the standard printer, or another specific printer, e.g. a laser printer or so like, selectable by printer name. Like with the `lp` command in (example) `lp -d MFC7820N` can we have (example) `paperbank -d MFC7820N` ?

**Comment by makevoid** [comment]
this is an old project I'm freezing it
