### ISSUE TITLE
Disappearing Thermal Ink - BEWARE

### ISSUE THREAD

**Issue by dagelf** [makevoid/paperbank#2]
If you think your thermal-printed paper wallet will still be readable in a few months' time, you are an optimist! Don't trust thermal paper!

**Comment by makevoid** [comment]
That's somewhat true, few months if exposed to light, but in the dark most of them they're rated 5-7 years, of course you should also protect them against fire / heat sources! You should make multiple copies of them, just use a copy machine laser/inkjet or even better a CNCed aluminium BIP38 private key! These are my suggestions, what do you think?

**Comment by makevoid** [comment]
https://github.com/makevoid/paperbank-pocket

In this repo you can find a easily-printable (via normal, non-thermal, printer and printer paper) web version of basically the same thing, a private key, qr code enabled, generator.

**Comment by makevoid** [comment]
closing this issue with a comment as this is a general problem for paper wallets

Crypto Steel or other similar products/solutions are recommended for cold private key backup.

BIP-39 Passphrase (mnemonic + passphrase) is the recommended way to secure your private keys.
